# Generated by Django 4.1.2 on 2022-11-13 23:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_jugador_fechacrracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='fechacrracion',
            field=models.DateField(),
        ),
    ]
