# Generated by Django 4.1.2 on 2022-12-13 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_jugador_descripcion_alter_jugador_fechacrracion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='fechacrracion',
            new_name='fechacreacion',
        ),
    ]
